name: ROS 2 Colcon Build CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup ROS 2 Jazzy
        uses: ros-tooling/setup-ros@v0.7
        with:
          ros-distro: jazzy

      - name: Cache Pip Packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python Dependencies
        run: |
          if [ ! -d "venv" ]; then
            python3 -m venv venv
            source venv/bin/activate
            pip install "numpy<2" 
            pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
            pip install onnxruntime  # CPU version (onnxruntime-gpu is huge)
            pip install ultralytics opencv-python onnx pygame carla==0.9.16
          else
            source venv/bin/activate
            echo "Using cached venv"
          fi

      - name: Colcon Build
        run: |
          source /opt/ros/jazzy/setup.bash
          source venv/bin/activate
          colcon build --symlink-install
        working-directory: ${{ github.workspace }}

      # - name: Run Linters
      #   run: |
      #     source /opt/ros/jazzy/setup.bash
      #     source install/setup.bash
      #     colcon test --packages-select hydrakon_camera --ament-flake8 --ament-pep257
