name: ROS 2 Colcon Build CI

on:
  push:
    branches:
      - main
      - nav2
    paths:
      - 'src/**'
      - '.github/workflows/colcon_build_ci.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/colcon_build_ci.yaml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:jazzy-ros-base
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install System Dependencies
        run: |
          apt-get update && apt-get install -y \
            python3-pip \
            python3-venv \
            git \
            wget
          rm -rf /var/lib/apt/lists/*

      - name: Cache Pip Packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            venv
          key: ${{ runner.os }}-pip-cpu-v2
          restore-keys: |
            ${{ runner.os }}-pip-cpu-v2-

      - name: Install Python Dependencies
        run: |
          if [ ! -d "venv" ]; then
            python3 -m venv venv --system-site-packages

            touch venv/COLCON_IGNORE
            
            . venv/bin/activate
                        
            pip install "numpy<2"
            pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
            pip install onnxruntime
            pip install ultralytics opencv-python onnx pygame carla==0.9.16
          else
            echo "Using cached venv"
          fi

      - name: Colcon Build
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          
          . venv/bin/activate
          
          colcon build --symlink-install --packages-ignore hydrakon_description vision_msgs vision_msgs_rviz_plugins